import axios from 'axios'

export const HOBBYS_FILTER = 'HOBBYS_FILTER'

export default {
  async getHobbysList ({ commit }) {
    const response = await axios.get('http://localhost:4000/hwahae/100')

    this.state.hobbysList.push(response.data)
    commit('getHobbysList')
  }
}
// ("HKZBREIXVA"),
// ("DMCPUEWYZN"),
// ("QVRDUSNWIX"),
// ("BKFEHRVZNQ"),
// ("LIEQHYTFAM"),
// ("WYXFMNDOJR"),
// ("PSHRKJMENT"),
// ("TMFOEQRNVX"),
// ("NIOWXPJQGU"),
// ("ETNHQPLROC"),
// ("EFWZDMTJHV"),
// ("MDGCPFHYLT"),
// ("XKOZUMNPAB"),
// ("HCSBDQFPLJ"),
// ("PVUOTDJLBN"),
// ("GBFCLPMEIQ"),
// ("DPLXBRNCSG"),
// ("YDVHUXKAJM"),
// ("YSMJNGPQHD"),
// ("OZEMAKDFVH"),
// ("MNQEAODVYI"),
// ("BMTVFALHNQ"),
// ("YMPTRQGLJH"),
// ("QSPHXEIVYW"),
// ("FMAQOKTSZX"),
// ("IXNYCBOHQM"),
// ("RKYMDOQCHN"),
// ("MHNQWTZJPY"),
// ("GTPKOICSLF"),
// ("UENMAKVZGJ"),
// ("YBXWMKLPRI"),
// ("YDQIWCOJAF"),
// ("QIWUZKLSHT"),
// ("YHRBJSIZCU"),
// ("HGLBTCFPNK"),
// ("BLXUHJTDVW"),
// ("RINYLQBASV"),
// ("ZOLTUFBCHR"),
// ("NTCFWPAOHD"),
// ("DBJOQCXLIU"),
// ("DVNASCBOPR"),
// ("OPBVUETSCM"),
// ("FJMVATQNGC"),
// ("LAWZBQSXKN"),
// ("KBPWOEIHYV"),
// ("EALZCWJGRF"),
// ("IXKYSVQZAT"),
// ("WTCIEGFMLV"),
// ("PGITVMZCXL"),
// ("KICEUGQSLF"),
// ("GTLQVFADON"),
// ("TSKNLXCFOG"),
// ("WXQSMZNVEP"),
// ("BYJLOIHWGA"),
// ("FELSGVHMXN"),
// ("BYCAEOQHVR"),
// ("VZUPLQGIJN"),
// ("YFPBERWOUV"),
// ("ZCWXOVESHF"),
// ("RULESGQPDW"),
// ("BCOKMTAIUY"),
// ("TZLCOHXIWG"),
// ("RWZMNHOJTG"),
// ("ALJISBZWKX"),
// ("PUSCYKJIOF"),
// ("MUQIROZGSK"),
// ("BMEOKLICRF"),
// ("TYRASPWLIN"),
// ("XOQCRZSAUB"),
// ("QIEAVUTSLC"),
// ("BVFIRAGMXL"),
// ("YSBWJAKLUR"),
// ("RNEZVBDOMA"),
// ("TDAMCRHEXI"),
// ("IWCMRBHVQJ"),
// ("AQHBMIYNEV"),
// ("KIJUWNEATM"),
// ("SQZYJHOFMG"),
// ("FRYSOIDLZX"),
// ("LFHRTEWXOA"),
// ("NAWEKUJFTP"),
// ("ZGCMXOSRED"),
// ("ESKXNZBOIQ"),
// ("WEFXGZJQBP"),
// ("PJXFWVKTZG"),
// ("OGECQSFZLM"),
// ("FLUBKDZNTP"),
// ("EKCHGVXLDA"),
// ("KDARBXYJVI"),
// ("HUBDNELAJY"),
// ("QRYJKTMSOW"),
// ("VFQGYHKWTA"),
// ("PEGRQWBXTS"),
// ("RUAQITBFHK"),
// ("KFIZEANBWD"),
// ("LSATHXQMCD"),
// ("WKYPEOACUN"),
// ("XMHZEIYNAD"),
// ("RWANOMCUVI"),
// ("THRKSBDQUO");
